### ISSUE TITLE
nextcord.ext.commands is missing a py.typed file

### ISSUE THREAD

**Issue by ooliver1** [nextcord/nextcord#770]
### Summary

nextcord.ext.commands is missing a py.typed file for type checkers

### Reproduction Steps

1. Install pyright, using (p)npm/yarn or an editor extension
2. Enable strict mode
3. Use below code
4. See error listed in actual results

### Minimal Reproducible Code

```python
from nextcord.ext.commands import command
```

### Expected Results

`nextcord.ext.commands` to be recognised to have inline PEP484 type hints.

### Actual Results

```py
Stub file not found for "nextcord.ext.commands"Pylance[reportMissingTypeStubs](https://github.com/microsoft/pylance-release/blob/main/DIAGNOSTIC_SEVERITY_RULES.md#diagnostic-severity-rules)
```

### Intents

N/A

### System Information

```
- Python v3.10.4-final
- nextcord v2.1.0-final
- aiohttp v3.8.1
- system info: Linux 5.15.0-43-generic #46-Ubuntu SMP Tue Jul 12 10:30:17 UTC 2022
```

### Checklist

- [X] I have searched the open issues for duplicates.
- [X] I have shown the entire traceback, if possible.
- [X] I have removed my token from display, if visible.

**Comment by teaishealthy** [comment]
cannot reproduce

**Comment by teaishealthy** [comment]
I can do this
